### ISSUE TITLE
The network don't learning with other dataset

### ISSUE THREAD

**Issue by AldrichCabrera** [vishnu-ks/AudioNet#4]
Hi, I have been a problem when trying to train the network with spectrograms creates from audio streaming in real-time. I collected 8k images, 4k for each folder. The spectrograms didn't create with .wav files.  It is the only different about your approach.  

Do you have any idea about this? My spectrogram images have a resolution of 553x396.

**Comment by iamvishnuks** [comment]
Glad to hear from you Aldrich!
I may need more information to answer your questions,
1. What type of audio you are trying to classify?
2. Is it noisier?
3. Where you able to successfully train the model?
